name: Publish to GitHub Packages

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (optional - will use package.json version if not provided)'
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@codeminds-digital'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests (if any)
        run: npm test --if-present
        
      - name: Build package
        run: npm run build

      - name: Update version if provided
        if: github.event.inputs.version
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Configure npm authentication
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "@codeminds-digital:registry=https://npm.pkg.github.com" >> ~/.npmrc
          cat ~/.npmrc

      - name: Verify authentication
        run: |
          echo "Checking npm whoami..."
          npm whoami --registry=https://npm.pkg.github.com || echo "whoami failed"
          echo "Checking package info..."
          npm view @codeminds-digital/pdfme-complete --registry=https://npm.pkg.github.com || echo "package not found (expected for first publish)"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
